### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by M0dred** [APTRS/APTRS#18]
# Make sure you have gone through the Documentation
https://anof-cyber.github.io/APTRS/#/

**Describe the bug**
run ./install.sh error

**To Reproduce**
1. sudo chmod +x install.sh
2. sudo ./install.sh
3. error...

**Screenshots**

Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 355, in execute
    return Database.Cursor.execute(self, query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: table "django_content_type" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kowalski/tools/APTRS/manage.py", line 22, in <module>
    main()
  File "/home/kowalski/tools/APTRS/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 447, in create_model
    self.execute(sql, params or None)
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kowalski/tools/APTRS/venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 355, in execute
    return Database.Cursor.execute(self, query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: table "django_content_type" already exists
./install.sh: line 42: wkhtmltopdf: command not found
Download and Install wkhtmltopdf Version 0.12.6 for PDF Report Generation - https://wkhtmltopdf.org/downloads.html

**Desktop (please complete the following information):**
 - OS: Kali purple
 - Python Version [3.11]
 - Pip Version[23.0.1]

**Comment by Anof-cyber** [comment]
Reffer https://github.com/Anof-cyber/APTRS/issues/13
